version: '3'
services:
  test-db:
    image: postgres
    container_name: test-postgres
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - test-postgresql-data:/var/lib/postgresql/data
    ports:
      - "5454:5432"
volumes:
  test-postgresql-data: